name: corelife
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0  
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.2  
  flutter_lints: ^5.0.0
  provider: ^6.1.3
  go_router: ^15.1.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  fl_chart: ^1.0.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - .env

dependency_overrides:

