// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5nN7GEn65QwjT5vSlsSHq7MQmhRgV_s',
    appId: '1:605305531825:web:8ed1f3900ccf8693606190',
    messagingSenderId: '605305531825',
    projectId: 'proyectocorelife',
    authDomain: 'proyectocorelife.firebaseapp.com',
    storageBucket: 'proyectocorelife.firebasestorage.app',
    measurementId: 'G-S4HNNJGC33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdyf3lzCyd-XxL5OuHXBQgkqRSRbcwMA',
    appId: '1:605305531825:android:dbf5e8f8bc8cf74d606190',
    messagingSenderId: '605305531825',
    projectId: 'proyectocorelife',
    storageBucket: 'proyectocorelife.firebasestorage.app',
  );
}
